/**
 * Music database containing songs with emotion classifications and popularity ratings.
 * Each song object includes: song title, artist name, emotion category, and popularity score.
 * 
 * Emotion categories include:
 * - Happy: Upbeat, joyful songs
 * - Sad: Melancholic, sorrowful songs  
 * - Energetic: High-energy, upbeat songs
 * - Calm: Peaceful, soothing songs
 * - Romantic: Love songs and romantic ballads
 * - Mellow: Relaxed, laid-back songs
 * - Relaxed: Chill, easy-going songs
 * - Depressed: Deeply sad, introspective songs
 * - Angry: Intense, aggressive songs
 * 
 * Popularity is rated on a scale of 0-100 based on streaming data.
 */
export const songs = [
    { song: 'My Life Would Suck Without You', artist: 'Kelly Clarkson', emotion: 'Energetic', popularity: 53 },
    { song: 'Verano Azul', artist: 'Juan Magán', emotion: 'Happy', popularity: 65 },
    { song: 'Let\'s Get Crazy', artist: 'Hannah Montana', emotion: 'Happy', popularity: 52 },
    { song: "I've Got The World On A String", artist: "Anita O'Day, Oscar Peterson Quartet", emotion: 'Calm', popularity: 16 },
    { song: "Mamita Mia - Remastered", artist: "Frente Popular", emotion: 'Relaxed', popularity: 2 },
    { song: "Puccini: Madama Butterfly, Act 2: \"Che tua madre dovrà\" (Butterfly)", artist: "Giacomo Puccini, Maria Callas, Herbert von Karajan", emotion: 'Sad', popularity: 13 },
    { song: "Stare It Cold", artist: "The Black Crowes", emotion: 'Energetic', popularity: 36 },
    { song: "Violin Concerto No. 1 in G Minor, Op. 26: II. Adagio", artist: "Max Bruch, Isaac Stern, Eugene Ormandy", emotion: 'Sad', popularity: 0 },
    { song: "On a Steamer Coming Over", artist: "Roy Fox", emotion: 'Calm', popularity: 1 },
    { song: "Leoncavallo: Pagliacci, Act I Scene 3: Non mi tentar!", artist: "Ruggero Leoncavallo, Alfredo Simonetto", emotion: 'Sad', popularity: 0 },
    { song: "Symphony No. 4 in E Minor, Op. 98: IV. Allegro energico e passionata", artist: "Johannes Brahms, Arturo Toscanini", emotion: 'Sad', popularity: 0 },
    { song: "Fat Lip", artist: "Sum 41", emotion: 'Energetic', popularity: 72 },
    { song: "Instant Music (Two Beat Society)", artist: "Nelson Riddle", emotion: 'Romantic', popularity: 12 },
    { song: "I'm Getting Sentimental Over You (Reprise)", artist: "Frank Sinatra", emotion: 'Sad', popularity: 10 },
    { song: "Money Bag", artist: "Cardi B", emotion: 'Energetic', popularity: 60 },
    { song: "Cool Blues", artist: "Sonny Stitt", emotion: 'Mellow', popularity: 5 },
    { song: "Go Go", artist: "BTS", emotion: 'Happy', popularity: 65 },
    { song: "Schön Rosmarin", artist: "Fritz Kreisler, Isaac Stern", emotion: 'Calm', popularity: 2 },
    { song: "Prabhu Laaj Bhakton Ki Rakhe Sada", artist: "Ratnaprabha", emotion: 'Calm', popularity: 0 },
    { song: "Do What You Want", artist: "Bad Religion", emotion: 'Energetic', popularity: 47 },
    { song: "Red Rubber Ball", artist: "The Cyrkle", emotion: 'Romantic', popularity: 42 },
    { song: "End Of Act 1: Memory", artist: "Andrew Lloyd Webber, Cats Original London Cast", emotion: 'Sad', popularity: 49 },
    { song: "Moody River", artist: "Johnny Burnette, The Johnny Mann Singers", emotion: 'Romantic', popularity: 13 },
    { song: "Twisting by the Pool", artist: "Dire Straits", emotion: 'Energetic', popularity: 34 },
    { song: "You Can't Stop the Beat - Medley", artist: "Laura Bell Bundy, Matthew Morrison, Linda Hart", emotion: 'Energetic', popularity: 43 },
    { song: "Fast Asleep", artist: "Paige Morehead", emotion: 'Calm', popularity: 32 },
    { song: "Justo el 31 - Remasterizado", artist: "Francisco Canaro", emotion: 'Calm', popularity: 0 },
    { song: "A Midsummer Night's Dream. Incidental Music, Op. 61: Scherzo - Remastered", artist: "Felix Mendelssohn, Bruno Walter", emotion: 'Relaxed', popularity: 0 },
    { song: "The Two Priests", artist: "Archibald MacLeish", emotion: 'Sad', popularity: 1 },
    { song: "Spybreak! - Short One", artist: "Propellerheads", emotion: 'Energetic', popularity: 44 },
    { song: "Undecided", artist: "George Shearing Quintet", emotion: 'Happy', popularity: 5 },
    { song: "Now They Call It Swing - Take 1", artist: "Billie Holiday", emotion: 'Relaxed', popularity: 2 },
    { song: "Strictly Rule", artist: "Vetiver", emotion: 'Romantic', popularity: 43 },
    { song: "Canadian Sunset - Single Version", artist: "Eddie Heywood", emotion: 'Relaxed', popularity: 25 },
    { song: "Anthony Boy", artist: "Chuck Berry", emotion: 'Happy', popularity: 28 },
    { song: "Trois Melodies: La Statue de bronze", artist: "Erik Satie, Pierre Bernac", emotion: 'Calm', popularity: 11 },
    { song: "Her Ghost in the Fog", artist: "Cradle Of Filth", emotion: 'Energetic', popularity: 45 },
    { song: "Living in America - From \"Rocky IV\" Soundtrack", artist: "James Brown", emotion: 'Happy', popularity: 54 },
    { song: "You're Getting To Be A Habit With Me - Remastered 1998", artist: "Frank Sinatra", emotion: 'Mellow', popularity: 35 },
    { song: "Zigeunerweisen, Op. 20: Un poco più lento", artist: "Pablo de Sarasate, William Steinberg", emotion: 'Depressed', popularity: 6 },
    { song: "Up the Down Escalator", artist: "The Chameleons", emotion: 'Energetic', popularity: 39 },
    { song: "TROJAN HORSE", artist: "SEBASTIAN PAUL", emotion: 'Happy', popularity: 61 },
    { song: "Wavelength - Remastered", artist: "Van Morrison", emotion: 'Energetic', popularity: 46 },
    { song: "My Heart Stood Still - Live", artist: "Bill Evans Trio", emotion: 'Mellow', popularity: 17 },
    { song: "People Say", artist: "The Dixie Cups", emotion: 'Romantic', popularity: 23 },
    { song: "Fu Man Chu", artist: "Desmond Dekker, The Aces", emotion: 'Romantic', popularity: 47 },
    { song: "Pocketful of Sunshine", artist: "Natasha Bedingfield", emotion: 'Happy', popularity: 63 },
    { song: "Bohemian Rhapsody", artist: "Queen", emotion: 'Energetic', popularity: 85 },
    { song: "Clair de Lune", artist: "Claude Debussy", emotion: 'Calm', popularity: 78 },
    { song: "Blinding Lights", artist: "The Weeknd", emotion: 'Energetic', popularity: 90 },
    { song: "Imagine", artist: "John Lennon", emotion: 'Calm', popularity: 80 },
    { song: "Shape of You", artist: "Ed Sheeran", emotion: 'Happy', popularity: 95 },
    { song: "Stairway to Heaven", artist: "Led Zeppelin", emotion: 'Calm', popularity: 85 },
    { song: "Let It Be", artist: "The Beatles", emotion: 'Sad', popularity: 88 },
    { song: "Billie Jean", artist: "Michael Jackson", emotion: 'Energetic', popularity: 92 },
    { song: "Hallelujah", artist: "Leonard Cohen", emotion: 'Sad', popularity: 75 },
    { song: "Someone Like You", artist: "Adele", emotion: 'Sad', popularity: 82 },
    { song: "Uptown Funk", artist: "Mark Ronson, Bruno Mars", emotion: 'Happy', popularity: 91 },
    { song: "Yesterday", artist: "The Beatles", emotion: 'Sad', popularity: 77 },
    { song: "Hotel California", artist: "Eagles", emotion: 'Calm', popularity: 84 },
    { song: "Lose Yourself", artist: "Eminem", emotion: 'Energetic', popularity: 89 },
    { song: "Rolling in the Deep", artist: "Adele", emotion: 'Energetic', popularity: 88 },
    { song: "What's Going On", artist: "Marvin Gaye", emotion: 'Relaxed', popularity: 70 },
    { song: "Purple Rain", artist: "Prince", emotion: 'Sad', popularity: 85 },
    { song: "Smells Like Teen Spirit", artist: "Nirvana", emotion: 'Energetic', popularity: 90 },
    { song: "Superstition", artist: "Stevie Wonder", emotion: 'Happy', popularity: 88 },
    { song: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", emotion: 'Sad', popularity: 83 },
    { song: "Firework", artist: "Katy Perry", emotion: 'Energetic', popularity: 87 },
    { song: "Thriller", artist: "Michael Jackson", emotion: 'Energetic', popularity: 93 },
    { song: "Like a Rolling Stone", artist: "Bob Dylan", emotion: 'Sad', popularity: 80 },
    { song: "Respect", artist: "Aretha Franklin", emotion: 'Energetic', popularity: 84 },
    { song: "Good Vibrations", artist: "The Beach Boys", emotion: 'Happy', popularity: 86 },
    { song: "Hey Jude", artist: "The Beatles", emotion: 'Sad', popularity: 89 },
    { song: "Sweet Child O' Mine", artist: "Guns N' Roses", emotion: 'Energetic', popularity: 88 },
    { song: "Dancing Queen", artist: "ABBA", emotion: 'Happy', popularity: 85 },
    { song: "Wonderwall", artist: "Oasis", emotion: 'Sad', popularity: 87 },
    { song: "Boogie Wonderland", artist: "Earth, Wind & Fire", emotion: 'Energetic', popularity: 82 },
    { song: "Havana", artist: "Camila Cabello, Young Thug", emotion: 'Happy', popularity: 84 },
    { song: "Back to Black", artist: "Amy Winehouse", emotion: 'Sad', popularity: 81 },
    { song: "Can't Stop the Feeling!", artist: "Justin Timberlake", emotion: 'Happy', popularity: 87 },
    { song: "Take On Me", artist: "a-ha", emotion: 'Energetic', popularity: 83 },
    { song: "Smooth", artist: "Santana, Rob Thomas", emotion: 'Energetic', popularity: 86 },
    { song: "Don't Stop Believin'", artist: "Journey", emotion: 'Energetic', popularity: 88 },
    { song: "Stayin' Alive", artist: "Bee Gees", emotion: 'Energetic', popularity: 89 },
    { song: "Happy", artist: "Pharrell Williams", emotion: 'Happy', popularity: 93 },
    { song: "Let It Go", artist: "Idina Menzel", emotion: 'Energetic', popularity: 85 },
    { song: "Poker Face", artist: "Lady Gaga", emotion: 'Energetic', popularity: 84 },
    { song: "Call Me Maybe", artist: "Carly Rae Jepsen", emotion: 'Happy', popularity: 87 },
    { song: "Roar", artist: "Katy Perry", emotion: 'Energetic', popularity: 86 },
    { song: "Hello", artist: "Adele", emotion: 'Sad', popularity: 89 },
    { song: "Wake Me Up", artist: "Avicii", emotion: 'Energetic', popularity: 88 },
    { song: "Lean On", artist: "Major Lazer, DJ Snake, MØ", emotion: 'Energetic', popularity: 85 },
    { song: "Cheap Thrills", artist: "Sia, Sean Paul", emotion: 'Happy', popularity: 84 },
    { song: "Love Me Like You Do", artist: "Ellie Goulding", emotion: 'Romantic', popularity: 87 },
    { song: "Can't Feel My Face", artist: "The Weeknd", emotion: 'Energetic', popularity: 88 },
    { song: "Faded", artist: "Alan Walker", emotion: 'Sad', popularity: 89 },
    { song: "Take Me to Church", artist: "Hozier", emotion: 'Sad', popularity: 83 },
    { song: "Despacito", artist: "Luis Fonsi, Daddy Yankee", emotion: 'Happy', popularity: 92 },
    { song: "See You Again", artist: "Wiz Khalifa, Charlie Puth", emotion: 'Sad', popularity: 90 },
    { song: "Thinking Out Loud", artist: "Ed Sheeran", emotion: 'Romantic', popularity: 88 },
    { song: "Stressed Out", artist: "Twenty One Pilots", emotion: 'Sad', popularity: 85 },
    { song: "Bad Guy", artist: "Billie Eilish", emotion: 'Energetic', popularity: 89 },
    { song: "Old Town Road", artist: "Lil Nas X, Billy Ray Cyrus", emotion: 'Happy', popularity: 91 },
    { song: "Sunflower", artist: "Post Malone, Swae Lee", emotion: 'Happy', popularity: 90 },
    { song: "Shallow", artist: "Lady Gaga, Bradley Cooper", emotion: 'Sad', popularity: 89 },
    { song: "Señorita", artist: "Shawn Mendes, Camila Cabello", emotion: 'Romantic', popularity: 92 },
    { song: "Perfect", artist: "Ed Sheeran", emotion: 'Romantic', popularity: 91 },
    { song: "Dance Monkey", artist: "Tones and I", emotion: 'Energetic', popularity: 90 },
    { song: "Watermelon Sugar", artist: "Harry Styles", emotion: 'Happy', popularity: 89 },
    { song: "Levitating", artist: "Dua Lipa", emotion: 'Energetic', popularity: 90 },
    { song: "Peaches", artist: "Justin Bieber, Daniel Caesar, Giveon", emotion: 'Happy', popularity: 88 },
    { song: "Save Your Tears", artist: "The Weeknd", emotion: 'Sad', popularity: 89 },
    { song: "drivers license", artist: "Olivia Rodrigo", emotion: 'Sad', popularity: 91 },
    { song: "MONTERO (Call Me By Your Name)", artist: "Lil Nas X", emotion: 'Energetic', popularity: 90 },
    { song: "Stay", artist: "The Kid LAROI, Justin Bieber", emotion: 'Energetic', popularity: 91 },
    { song: "Good 4 U", artist: "Olivia Rodrigo", emotion: 'Energetic', popularity: 92 },
    { song: "Heat Waves", artist: "Glass Animals", emotion: 'Sad', popularity: 89 },
    { song: "Industry Baby", artist: "Lil Nas X, Jack Harlow", emotion: 'Energetic', popularity: 93 },
    { song: "Bad Habits", artist: "Ed Sheeran", emotion: 'Energetic', popularity: 92 },
    { song: "Easy On Me", artist: "Adele", emotion: 'Sad', popularity: 90 },
    { song: "Summer Days", artist: "Martin Garrix, Macklemore, Fall Out Boy", emotion: 'Energetic', popularity: 74 },
    { song: "Love Me Like That", artist: "R5", emotion: 'Romantic', popularity: 43 },
    { song: "Another Part of Me", artist: "Michael Jackson", emotion: 'Happy', popularity: 52 },
    { song: "She Caught The Katy", artist: "The Blues Brothers", emotion: 'Happy', popularity: 44 },
    { song: "Born in East L.A.", artist: "Cheech & Chong", emotion: 'Happy', popularity: 26 },
    { song: "How Deep Is Your Love", artist: "Sean Paul", emotion: 'Romantic', popularity: 56 },
    { song: "Somebody Loves Me", artist: "Perry Como", emotion: 'Happy', popularity: 18 },
    { song: "Season Of The Witch", artist: "Joan Jett & The Blackhearts", emotion: 'Energetic', popularity: 41 },
    { song: "Medal of Honor", artist: "C. S. Armstrong", emotion: 'Happy', popularity: 25 },
    { song: "Never Met", artist: "Cautious Clay", emotion: 'Sad', popularity: 43 },
    { song: "Enter the Eternal Fire", artist: "Bathory", emotion: 'Angry', popularity: 33 }
];
