/**
 * Music database containing songs with emotion classifications and popularity ratings.
 * Each song object includes: song title, artist name, emotion category, and popularity score.
 * 
 * Emotion categories include:
 * - Happy: Upbeat, joyful songs
 * - Sad: Melancholic, sorrowful songs  
 * - Energetic: High-energy, upbeat songs
 * - Calm: Peaceful, soothing songs
 * - Romantic: Love songs and romantic ballads
 * - Mellow: Relaxed, laid-back songs
 * - Relaxed: Chill, easy-going songs
 * - Depressed: Deeply sad, introspective songs
 * - Angry: Intense, aggressive songs
 * 
 * Popularity is rated on a scale of 0-100 based on streaming data.
 */
export const songs = [
    { song: 'My Life Would Suck Without You', artist: 'Kelly Clarkson', emotion: 'Energetic', popularity: 53 },
    { song: 'Verano Azul', artist: 'Juan Magán', emotion: 'Happy', popularity: 65 },
    { song: 'Let\'s Get Crazy', artist: 'Hannah Montana', emotion: 'Happy', popularity: 52 },
    { song: "I've Got The World On A String", artist: "Anita O'Day, Oscar Peterson Quartet", emotion: 'Calm', popularity: 16 },
    { song: "Mamita Mia - Remastered", artist: "Frente Popular", emotion: 'Relaxed', popularity: 2 },
    { song: "Puccini: Madama Butterfly, Act 2: \"Che tua madre dovrà\" (Butterfly)", artist: "Giacomo Puccini, Maria Callas, Herbert von Karajan, Orchestra Del Teatro Alla Scala, Milano", emotion: 'Sad', popularity: 13 },
    { song: "Stare It Cold", artist: "The Black Crowes", emotion: 'Energetic', popularity: 36 },
    { song: "Violin Concerto No. 1 in G Minor, Op. 26: II. Adagio", artist: "Max Bruch, Isaac Stern, Eugene Ormandy, Philadelphia Orchestra", emotion: 'Sad', popularity: 0 },
    { song: "On a Steamer Coming Over", artist: "Roy Fox", emotion: 'Calm', popularity: 1 },
    { song: "Leoncavallo: Pagliacci, Act I Scene 3: Non mi tentar! (Nedda, Silvio, Tonio)", artist: "Ruggero Leoncavallo, Alfredo Simonetto, Carla Gavazzi, Marcello Rossi, Carlo Tagliabue, Orchestra Sinfonica e Coro di Milano della RAI", emotion: 'Sad', popularity: 0 },
    { song: "Symphony No. 4 in E Minor, Op. 98: IV. Allegro energico e passionata", artist: "Johannes Brahms, Arturo Toscanini", emotion: 'Sad', popularity: 0 },
    { song: "Fat Lip", artist: "Sum 41", emotion: 'Energetic', popularity: 72 },
    { song: "Instant Music (Two Beat Society)", artist: "Nelson Riddle", emotion: 'Romantic', popularity: 12 },
    { song: "I'm Getting Sentimental Over You (Reprise)", artist: "Frank Sinatra", emotion: 'Sad', popularity: 10 },
    { song: "Money Bag", artist: "Cardi B", emotion: 'Energetic', popularity: 60 },
    { song: "Cool Blues", artist: "Sonny Stitt", emotion: 'Mellow', popularity: 5 },
    { song: "Go Go", artist: "BTS", emotion: 'Happy', popularity: 65 },
    { song: "Schön Rosmarin", artist: "Fritz Kreisler, Isaac Stern", emotion: 'Calm', popularity: 2 },
    { song: "Prabhu Laaj Bhakton Ki Rakhe Sada", artist: "Ratnaprabha", emotion: 'Calm', popularity: 0 },
    { song: "Do What You Want", artist: "Bad Religion", emotion: 'Energetic', popularity: 47 },
    { song: "Red Rubber Ball", artist: "The Cyrkle", emotion: 'Romantic', popularity: 42 },
    { song: "End Of Act 1: Memory", artist: "Andrew Lloyd Webber, \"Cats\" 1981 Original London Cast, Elaine Paige", emotion: 'Sad', popularity: 49 },
    { song: "Moody River", artist: "Johnny Burnette, The Johnny Mann Singers", emotion: 'Romantic', popularity: 13 },
    { song: "Twisting by the Pool", artist: "Dire Straits", emotion: 'Energetic', popularity: 34 },
    { song: "You Can't Stop the Beat - Medley", artist: "Laura Bell Bundy, Matthew Morrison, Linda Hart", emotion: 'Energetic', popularity: 43 },
    { song: "Fast Asleep", artist: "Paige Morehead", emotion: 'Calm', popularity: 32 },
    { song: "Οι δυο σερέτες", artist: "Αντώνης Νταλγκάς", emotion: 'Relaxed', popularity: 0 },
    { song: "Justo el 31 - Remasterizado", artist: "Francisco Canaro", emotion: 'Calm', popularity: 0 },
    { song: "A Midsummer Night's Dream. Incidental Music, Op. 61: Scherzo - Remastered", artist: "Felix Mendelssohn, Bruno Walter, New York Philharmonic", emotion: 'Relaxed', popularity: 0 },
    { song: "The Two Priests", artist: "Archibald MacLeish", emotion: 'Sad', popularity: 1 },
    { song: "Spybreak! - Short One", artist: "Propellerheads", emotion: 'Energetic', popularity: 44 },
    { song: "Undecided", artist: "George Shearing Quintet", emotion: 'Happy', popularity: 5 },
    { song: "Now They Call It Swing - Take 1", artist: "Billie Holiday", emotion: 'Relaxed', popularity: 2 },
    { song: "Strictly Rule", artist: "Vetiver", emotion: 'Romantic', popularity: 43 },
    { song: "Canadian Sunset - Single Version", artist: "Eddie Heywood", emotion: 'Relaxed', popularity: 25 },
    { song: "Anthony Boy", artist: "Chuck Berry", emotion: 'Happy', popularity: 28 },
    { song: "Trois Melodies: La Statue de bronze", artist: "Erik Satie, Pierre Bernac, Francis Poulenc", emotion: 'Calm', popularity: 11 },
    { song: "Her Ghost in the Fog", artist: "Cradle Of Filth", emotion: 'Energetic', popularity: 45 },
    { song: "Living in America - From \"Rocky IV\" Soundtrack", artist: "James Brown", emotion: 'Happy', popularity: 54 },
    { song: "You're Getting To Be A Habit With Me - Remastered 1998", artist: "Frank Sinatra", emotion: 'Mellow', popularity: 35 },
    { song: "Zigeunerweisen, Op. 20: Un poco più lento", artist: "Pablo de Sarasate, William Steinberg, Jascha Heifetz", emotion: 'Depressed', popularity: 6 },
    { song: "Up the Down Escalator", artist: "The Chameleons", emotion: 'Energetic', popularity: 39 },
    { song: "O Nargis Pyare", artist: "Dilshad Begum", emotion: 'Relaxed', popularity: 0 },
    { song: "TROJAN HORSE", artist: "SEBASTIAN PAUL", emotion: 'Happy', popularity: 61 },
    { song: "Wavelength - Remastered", artist: "Van Morrison", emotion: 'Energetic', popularity: 46 },
    { song: "My Heart Stood Still - Live", artist: "Bill Evans Trio", emotion: 'Mellow', popularity: 17 },
    { song: "People Say", artist: "The Dixie Cups", emotion: 'Romantic', popularity: 23 },
    { song: "Fu Man Chu", artist: "Desmond Dekker, The Aces", emotion: 'Romantic', popularity: 47 },
    { song: "Pocketful of Sunshine", artist: "Natasha Bedingfield", emotion: 'Happy', popularity: 63 },
    { song: "I Puritani (1986 - Remaster), Act III: Ch'ei provò lontan da me?", artist: "Carlo Pepoli, Vincenzo Bellini, Maria Callas, Giuseppe Di Stefano, Orchestra Del Teatro Alla Scala, Milano, Tullio Serafin, Orchestra Del Teatro Alla Scala Di Milan", emotion: 'Sad', popularity: 0 },
    { song: "Take Me In Your Arms (Rock Me A Little While)", artist: "The Isley Brothers", emotion: 'Happy', popularity: 40 },
    { song: "Summertime", artist: "Ella Fitzgerald, Louis Armstrong", emotion: 'Relaxed', popularity: 60 },
    { song: "Bohemian Rhapsody", artist: "Queen", emotion: 'Energetic', popularity: 85 },
    { song: "Clair de Lune", artist: "Claude Debussy", emotion: 'Calm', popularity: 78 },
    { song: "Blinding Lights", artist: "The Weeknd", emotion: 'Energetic', popularity: 90 },
    { song: "Imagine", artist: "John Lennon", emotion: 'Sad', popularity: 80 },
    { song: "Shape of You", artist: "Ed Sheeran", emotion: 'Happy', popularity: 95 },
    { song: "Stairway to Heaven", artist: "Led Zeppelin", emotion: 'Calm', popularity: 85 },
    { song: "Let It Be", artist: "The Beatles", emotion: 'Sad', popularity: 88 },
    { song: "Billie Jean", artist: "Michael Jackson", emotion: 'Energetic', popularity: 92 },
    { song: "Hallelujah", artist: "Leonard Cohen", emotion: 'Sad', popularity: 75 },
    { song: "Someone Like You", artist: "Adele", emotion: 'Sad', popularity: 82 },
    { song: "Uptown Funk", artist: "Mark Ronson, Bruno Mars", emotion: 'Happy', popularity: 91 },
    { song: "Yesterday", artist: "The Beatles", emotion: 'Sad', popularity: 77 },
    { song: "Hotel California", artist: "Eagles", emotion: 'Calm', popularity: 84 },
    { song: "Lose Yourself", artist: "Eminem", emotion: 'Energetic', popularity: 89 },
    { song: "Rolling in the Deep", artist: "Adele", emotion: 'Energetic', popularity: 88 },
    { song: "What's Going On", artist: "Marvin Gaye", emotion: 'Relaxed', popularity: 70 },
    { song: "Purple Rain", artist: "Prince", emotion: 'Sad', popularity: 85 },
    { song: "Smells Like Teen Spirit", artist: "Nirvana", emotion: 'Energetic', popularity: 90 },
    { song: "Superstition", artist: "Stevie Wonder", emotion: 'Happy', popularity: 88 },
    { song: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", emotion: 'Sad', popularity: 83 },
    { song: "Firework", artist: "Katy Perry", emotion: 'Energetic', popularity: 87 },
    { song: "Thriller", artist: "Michael Jackson", emotion: 'Energetic', popularity: 93 },
    { song: "Like a Rolling Stone", artist: "Bob Dylan", emotion: 'Sad', popularity: 80 },
    { song: "Respect", artist: "Aretha Franklin", emotion: 'Energetic', popularity: 84 },
    { song: "Good Vibrations", artist: "The Beach Boys", emotion: 'Happy', popularity: 86 },
    { song: "Hey Jude", artist: "The Beatles", emotion: 'Sad', popularity: 89 },
    { song: "Sweet Child O' Mine", artist: "Guns N' Roses", emotion: 'Energetic', popularity: 88 },
    { song: "Dancing Queen", artist: "ABBA", emotion: 'Happy', popularity: 85 },
    { song: "Wonderwall", artist: "Oasis", emotion: 'Sad', popularity: 87 },
    { song: "Boogie Wonderland", artist: "Earth, Wind & Fire", emotion: 'Energetic', popularity: 82 },
    { song: "Havana", artist: "Camila Cabello, Young Thug", emotion: 'Happy', popularity: 84 },
    { song: "Back to Black", artist: "Amy Winehouse", emotion: 'Sad', popularity: 81 },
    { song: "Can't Stop the Feeling!", artist: "Justin Timberlake", emotion: 'Happy', popularity: 87 },
    { song: "Take On Me", artist: "a-ha", emotion: 'Energetic', popularity: 83 },
    { song: "Smooth", artist: "Santana, Rob Thomas", emotion: 'Energetic', popularity: 86 },
    { song: "Don't Stop Believin'", artist: "Journey", emotion: 'Energetic', popularity: 88 },
    { song: "Stayin' Alive", artist: "Bee Gees", emotion: 'Energetic', popularity: 89 },
    { song: "Imagine", artist: "John Lennon", emotion: 'Calm', popularity: 90 },
    { song: "Rolling in the Deep", artist: "Adele", emotion: 'Energetic', popularity: 92 },
    { song: "Happy", artist: "Pharrell Williams", emotion: 'Happy', popularity: 93 },
    { song: "Let It Go", artist: "Idina Menzel", emotion: 'Energetic', popularity: 85 },
    { song: "Poker Face", artist: "Lady Gaga", emotion: 'Energetic', popularity: 84 },
    { song: "Call Me Maybe", artist: "Carly Rae Jepsen", emotion: 'Happy', popularity: 87 },
    { song: "Roar", artist: "Katy Perry", emotion: 'Energetic', popularity: 86 },
    { song: "Hello", artist: "Adele", emotion: 'Sad', popularity: 89 },
    { song: "Wake Me Up", artist: "Avicii", emotion: 'Energetic', popularity: 88 },
    { song: "Lean On", artist: "Major Lazer, DJ Snake, MØ", emotion: 'Energetic', popularity: 85 },
    { song: "Cheap Thrills", artist: "Sia, Sean Paul", emotion: 'Happy', popularity: 84 },
    { song: "Love Me Like You Do", artist: "Ellie Goulding", emotion: 'Romantic', popularity: 87 },
    { song: "Can't Feel My Face", artist: "The Weeknd", emotion: 'Energetic', popularity: 88 },
    { song: "Faded", artist: "Alan Walker", emotion: 'Sad', popularity: 89 },
    { song: "Take Me to Church", artist: "Hozier", emotion: 'Sad', popularity: 83 },
    { song: "Despacito", artist: "Luis Fonsi, Daddy Yankee", emotion: 'Happy', popularity: 92 },
    { song: "See You Again", artist: "Wiz Khalifa, Charlie Puth", emotion: 'Sad', popularity: 90 },
    { song: "Thinking Out Loud", artist: "Ed Sheeran", emotion: 'Romantic', popularity: 88 },
    { song: "Stressed Out", artist: "Twenty One Pilots", emotion: 'Sad', popularity: 85 },
    { song: "Bad Guy", artist: "Billie Eilish", emotion: 'Energetic', popularity: 89 },
    { song: "Old Town Road", artist: "Lil Nas X, Billy Ray Cyrus", emotion: 'Happy', popularity: 91 },
    { song: "Sunflower", artist: "Post Malone, Swae Lee", emotion: 'Happy', popularity: 90 },
    { song: "Shallow", artist: "Lady Gaga, Bradley Cooper", emotion: 'Sad', popularity: 89 },
    { song: "Señorita", artist: "Shawn Mendes, Camila Cabello", emotion: 'Romantic', popularity: 92 },
    { song: "Perfect", artist: "Ed Sheeran", emotion: 'Romantic', popularity: 91 },
    { song: "Dance Monkey", artist: "Tones and I", emotion: 'Energetic', popularity: 90 },
    { song: "Blinding Lights", artist: "The Weeknd", emotion: 'Energetic', popularity: 95 },
    { song: "Rockstar", artist: "DaBaby, Roddy Ricch", emotion: 'Energetic', popularity: 88 },
    { song: "Watermelon Sugar", artist: "Harry Styles", emotion: 'Happy', popularity: 89 },
    { song: "Levitating", artist: "Dua Lipa", emotion: 'Energetic', popularity: 90 },
    { song: "Peaches", artist: "Justin Bieber, Daniel Caesar, Giveon", emotion: 'Happy', popularity: 88 },
    { song: "Save Your Tears", artist: "The Weeknd", emotion: 'Sad', popularity: 89 },
    { song: "drivers license", artist: "Olivia Rodrigo", emotion: 'Sad', popularity: 91 },
    { song: "MONTERO (Call Me By Your Name)", artist: "Lil Nas X", emotion: 'Energetic', popularity: 90 },
    { song: "Stay", artist: "The Kid LAROI, Justin Bieber", emotion: 'Energetic', popularity: 91 },
    { song: "Good 4 U", artist: "Olivia Rodrigo", emotion: 'Energetic', popularity: 92 },
    { song: "Heat Waves", artist: "Glass Animals", emotion: 'Sad', popularity: 89 },
    { song: "Industry Baby", artist: "Lil Nas X, Jack Harlow", emotion: 'Energetic', popularity: 93 },
    { song: "Bad Habits", artist: "Ed Sheeran", emotion: 'Energetic', popularity: 92 },
    { song: "Easy On Me", artist: "Adele", emotion: 'Sad', popularity: 90 },
    { song: "STAY", artist: "The Kid LAROI, Justin Bieber", emotion: 'Energetic', popularity: 91 },
    { song: 'Cariñito De Mi Vida (Versión Original) Remasterizada - Remaster', artist: 'Luis Segura', emotion: 'Happy', popularity: 25 },
    { song: 'When I Fall In Love', artist: 'Johnny Mathis', emotion: 'Sad', popularity: 28 },
    { song: 'Saldo: 0 - Remastered', artist: 'Maribel Llaudes', emotion: 'Relaxed', popularity: 0 },
    { song: 'A szerelem jó', artist: 'Kriszta Kovats', emotion: 'Happy', popularity: 0 },
    { song: 'Wonderful Rain', artist: 'Les Paul & Mary Ford', emotion: 'Relaxed', popularity: 10 },
    { song: 'El Mono', artist: 'Wilfrido Vargas', emotion: 'Happy', popularity: 46 },
    { song: 'Piano Concerto No. 2 in C Minor, Op. 18: III. Allegro scherzando', artist: 'Sergei Rachmaninoff', 'Eugene Ormandy', 'Philadelphia Orchestra', emotion: 'Sad', popularity: 0 },
    { song: 'Persona Ideal', artist: "Adolescent's Orquesta", emotion: 'Romantic', popularity: 61 },
    { song: 'The Real Old Mountain Dew', artist: 'The Clancy Brothers', 'Tommy Makem', emotion: 'Relaxed', popularity: 24 },
    { song: 'Volveré', artist: 'Diego Verdaguer', emotion: 'Relaxed', popularity: 60 },
    { song: 'Πειραιώτισσα', artist: 'Sotiria Bellou', 'Stellakis Perpiniadis', emotion: 'Relaxed', popularity: 0 },
    { song: 'La Bohème: Act I: Chi è là - Scusi. - Una donna!', artist: 'Giacomo Puccini', 'Arturo Toscanini', emotion: 'Sad', popularity: 2 },
    { song: 'We (feat. CeeLo Green)', artist: 'Mac Miller', 'CeeLo Green', emotion: 'Relaxed', popularity: 58 },
    { song: '12:51', artist: 'The Strokes', emotion: 'Energetic', popularity: 60 },
    { song: 'Steal My Sunshine - Single Version', artist: 'LEN', emotion: 'Energetic', popularity: 57 },
    { song: 'Mazurkas, Op. 68: No. 3 in F Major', artist: 'Frédéric Chopin', 'Arthur Rubinstein', emotion: 'Sad', popularity: 4 },
    { song: 'Bury Me (feat. Maria McKee)', artist: 'Dwight Yoakam', 'Maria McKee', emotion: 'Happy', popularity: 28 },
    { song: 'Chili Pepper', artist: 'Art Pepper', emotion: 'Relaxed', popularity: 12 },
    { song: 'Indiana', artist: 'Lennie Tristano', emotion: 'Calm', popularity: 6 },
    { song: 'The Rising of the Moon', artist: 'The Clancy Brothers', 'Tommy Makem', emotion: 'Calm', popularity: 17 },
    { song: 'El Ultimo Cartucho', artist: 'Los Invasores De Nuevo León', emotion: 'Happy', popularity: 47 },
    { song: 'Aaj Ki Raat Mohabbat Hai Jawan', artist: 'Suraiya', emotion: 'Relaxed', popularity: 0 },
    { song: "Feelin' Love", artist: 'Paula Cole', emotion: 'Romantic', popularity: 40 },
    { song: 'Lady in a Blue Dress', artist: 'Senses Fail', emotion: 'Energetic', popularity: 50 },
    { song: 'Someday, Someway', artist: 'The Marvelettes', emotion: 'Happy', popularity: 17 },
    { song: 'The Queen of White Lies', artist: 'The Orion Experience', emotion: 'Happy', popularity: 43 },
    { song: 'Don Segundo Sombra - Remasterizado', artist: 'Francisco Canaro', 'Charlo', emotion: 'Calm', popularity: 0 },
    { song: 'Yellow Brick Road', artist: 'Captain Beefheart & His Magic Band', emotion: 'Romantic', popularity: 30 },
    { song: 'Prem Ke Gile Panghat Pe Man Mera', artist: 'Kamal Dasgupta', emotion: 'Calm', popularity: 0 },
    { song: 'TROJAN HORSE', artist: 'SEBASTIAN PAUL', emotion: 'Happy', popularity: 61 },
    { song: 'Katzberg', artist: 'The Katzenjammers', emotion: 'Relaxed', popularity: 9 },
    { song: 'Tarzan (O Filho Do Alfaiate)', artist: 'Almirante', emotion: 'Relaxed', popularity: 0 },
    { song: 'Lonesome', artist: 'Cory Morrow', emotion: 'Energetic', popularity: 45 },
    { song: 'Futures', artist: 'Jimmy Eat World', emotion: 'Energetic', popularity: 43 },
    { song: "All Your'n", artist: 'Tyler Childers', emotion: 'Romantic', popularity: 69 },
    { song: "I'm Always Chasing Rainbows", artist: 'Tony Bennett', emotion: 'Sad', popularity: 18 },
    { song: 'Partita No. 3 in E Major, BWV 1006: III. Gavotte en Rondeau', artist: 'Johann Sebastian Bach', 'Jascha Heifetz', emotion: 'Calm', popularity: 0 },
    { song: 'LOVE SCENARIO', artist: 'iKON', emotion: 'Happy', popularity: 73 },
    { song: 'Mercury Blues', artist: 'Steve Miller Band', emotion: 'Romantic', popularity: 41 },
    { song: 'I Wanna Be Around', artist: 'Frank Sinatra', 'Count Basie', emotion: 'Mellow', popularity: 32 },
    { song: 'Moody River', artist: 'Johnny Burnette', 'The Johnny Mann Singers', emotion: 'Romantic', popularity: 13 },
    { song: "You Ku'uipo", artist: 'Willie K', emotion: 'Happy', popularity: 40 },
    { song: 'Leoncavallo: Pagliacci, Act I Scene 3: Non mi tentar! (Nedda, Silvio, Tonio)', artist: 'Ruggero Leoncavallo', 'Alfredo Simonetto', 'Carla Gavazzi', 'Marcello Rossi', 'Carlo Tagliabue', 'Orchestra Sinfonica e Coro di Milano della RAI', emotion: 'Sad', popularity: 0 },
    { song: 'Strong Island', artist: 'JVC Force', emotion: 'Happy', popularity: 35 },
    { song: 'Seis Pies Abajo', artist: 'Los Cadetes', emotion: 'Happy', popularity: 47 },
    { song: 'Alors on danse', artist: 'Stromae', emotion: 'Happy', popularity: 60 },
    { song: 'No Way Back', artist: 'Foo Fighters', emotion: 'Energetic', popularity: 56 },
    { song: 'A Love Supreme Pt. IV - Psalm - Live In Juan-les-Pins, France/1965', artist: 'John Coltrane', emotion: 'Relaxed', popularity: 13 },
    { song: "Too Shy To Say", artist: 'Stevie Wonder', emotion: 'Sad', popularity: 36 },
    { song: 'Take Me In Your Arms (Rock Me A Little While)', artist: 'The Isley Brothers', emotion: 'Happy', popularity: 28 },
    { song: 'Unica', artist: 'Ozuna', emotion: 'Happy', popularity: 69 },
    { song: 'Whatever Lola Wants', artist: 'Gwen Verdon', emotion: 'Calm', popularity: 23 },
    { song: 'Better Together', artist: 'Jack Johnson', emotion: 'Romantic', popularity: 1 },
    { song: 'Sweet Lucy', artist: 'Michael Hurley', 'Unholy Modal Rounders', 'Jeffrey Frederick & The Clamtones', emotion: 'Happy', popularity: 25 },
    { song: 'Voy Bien o Me Regreso', artist: 'Los Teen Tops', emotion: 'Romantic', popularity: 20 },
    { song: 'Folk Songs of Brazil: Engenho novo', artist: 'Antonio Francisco Braga', 'Bidu Sayão', emotion: 'Calm', popularity: 0 },
    { song: "A Midsummer Night's Dream. Incidental Music, Op. 61: Scherzo - Remastered", artist: 'Felix Mendelssohn', 'Bruno Walter', 'New York Philharmonic', emotion: 'Relaxed', popularity: 0 },
    { song: 'The Chill Air - 2004 Digital Remaster', artist: 'Brian Eno', 'Harold Budd', emotion: 'Sad', popularity: 37 },
    { song: "Baby's Gotten Good At Goodbye", artist: 'George Strait', emotion: 'Mellow', popularity: 45 },
    { song: 'Fu Man Chu', artist: 'Desmond Dekker', 'The Aces', emotion: 'Romantic', popularity: 47 },
    { song: 'Down', artist: 'R.K.M & Ken-Y', emotion: 'Happy', popularity: 63 },
    { song: 'Maiya Soona Mandir Tera', artist: 'Durga Khote', emotion: 'Calm', popularity: 0 },
    { song: 'Le sacre du printemps: Part 1 "Adoration of the Earth", Spring Rounds', artist: 'Igor Stravinsky', 'Columbia Symphony Orchestra', emotion: 'Sad', popularity: 1 },
    { song: 'Twice Inna Lifetime', artist: 'Black Star', 'Jane Doe', 'Punch', 'Words', emotion: 'Happy', popularity: 39 },
    { song: 'Summertime In The LBC', artist: 'Dove Shack', emotion: 'Mellow', popularity: 51 },
    { song: 'Volverás', artist: 'Los Terricolas', emotion: 'Romantic', popularity: 35 },
    { song: "I'm So Hood", artist: 'DJ Khaled', emotion: 'Energetic', popularity: 50 },
    { song: 'Tomorrow (We Will Meet Once More)', artist: 'Nina Simone', emotion: 'Calm', popularity: 12 },
    { song: 'Just One Of Those Things', artist: 'Ray Conniff', emotion: 'Happy', popularity: 24 },
    { song: 'Shostakovich: The Gadfly Suite, Op. 97a: VIII. Romance', artist: 'Dmitri Shostakovich', 'Tasmin Little', 'Piers Lane', emotion: 'Sad', popularity: 35 },
    { song: 'Prelude: The Ballad of Sweeney Todd: "Attend the Tale of Sweeney Todd"', artist: 'Stephen Sondheim', 'Len Cariou', 'Sweeney Todd: The Demon Barber of Fleet Street Original Broadway Cast Ensemble', 'Paul Gemignani', emotion: 'Sad', popularity: 32 },
    { song: 'Pampa - Instrumental (Remasterizado)', artist: 'Francisco Canaro', emotion: 'Happy', popularity: 0 },
    { song: 'No Te Veo - Digital Single', artist: 'Casa De Leones', emotion: 'Happy', popularity: 61 },
    { song: 'Hated', artist: 'Beartooth', emotion: 'Energetic', popularity: 60 },
    { song: 'Tragic Overture, Op. 81', artist: 'Johannes Brahms', 'Arturo Toscanini', emotion: 'Sad', popularity: 0 },
    { song: 'O komm im Traum S. 282', artist: 'Franz Liszt', 'Theodor Scheidl', 'Franz Rupp', emotion: 'Sad', popularity: 0 },
    { song: 'When You Wish Upon A Star - Pinocchio', artist: 'Rockabye Lullaby', emotion: 'Calm', popularity: 60 },
    { song: 'Run That Body Down', artist: 'Paul Simon', emotion: 'Relaxed', popularity: 48 },
    { song: 'It Must Be Love', artist: 'Alan Jackson', emotion: 'Happy', popularity: 31 },
    { song: "I Love Paris", artist: 'Dean Martin', emotion: 'Calm', popularity: 21 },
    { song: 'Plays Pretty for Baby', artist: 'Zolof the Rock & Roll Destroyer', emotion: 'Energetic', popularity: 38 },
    { song: 'Sonata, Op. 34, No. 2 in G Minor: III. Allegro molto', artist: 'Muzio Clementi', 'Vladimir Horowitz', emotion: 'Calm', popularity: 0 },
    { song: 'Homenaje A Carlos Y José', artist: 'Los Invasores De Nuevo León', emotion: 'Happy', popularity: 28 },
    { song: 'Blue Jeans', artist: 'Lana Del Rey', emotion: 'Energetic', popularity: 48 },
    { song: "Don't Hurt My Little Sister (Stereo)", artist: 'The Beach Boys', emotion: 'Relaxed', popularity: 13 },
    { song: 'Enter the Eternal Fire', artist: 'Bathory', emotion: 'Angry', popularity: 33 },
    { song: 'Palabras De Alma', artist: 'Marc Anthony', emotion: 'Energetic', popularity: 42 },
    { song: 'Γκαζέλι σεχνάζ', artist: 'Roza Eskenazi', emotion: 'Relaxed', popularity: 0 },
    { song: 'La Llorona', artist: 'Caifanes', emotion: 'Calm', popularity: 46 },
    { song: 'Pequeña Orgullosa', artist: 'Liberación', emotion: 'Happy', popularity: 30 },
    { song: 'Maria Elena', artist: 'Carolina Cardoso de Menezes', 'Garoto', emotion: 'Calm', popularity: 4 },
    { song: 'X-Ray Eyes', artist: 'KISS', emotion: 'Energetic', popularity: 35 },
    { song: 'Bossa Nova U.S.A.', artist: 'Dave Brubeck', emotion: 'Romantic', popularity: 42 },
    { song: "I Was Made for Dancin'", artist: 'Leif Garrett', emotion: 'Happy', popularity: 42 },
    { song: 'i think too much', artist: 'Christian French', emotion: 'Happy', popularity: 64 },
    { song: 'White Wedding - Pt. 1', artist: 'Billy Idol', emotion: 'Happy', popularity: 70 },
    { song: "You're Getting To Be A Habit With Me - Remastered 1998", artist: 'Frank Sinatra', emotion: 'Mellow', popularity: 35 },
    { song: '2 Times - Original', artist: 'Ann Lee', emotion: 'Happy', popularity: 57 },
    { song: 'Boogie Woogie Woman', artist: 'B.B. King', emotion: 'Energetic', popularity: 16 },
    { song: "Callin' Out", artist: 'Lyrics Born', 'Joyo Velarde', 'Gift Of Gab', 'Blackalicious', emotion: 'Happy', popularity: 46 },
    { song: 'Annie the Cop Fighter', artist: 'Alcoholics Anonymous', emotion: 'Relaxed', popularity: 0 },
    { song: 'Chifara - Stereo Master', artist: 'Mulatu Astatke', emotion: 'Romantic', popularity: 29 },
    { song: 'Lost In Emotion', artist: 'Lisa Lisa & Cult Jam', emotion: 'Happy', popularity: 41 },
    { song: 'Dance with Me (feat. Thomas Rhett & Young Thug)', artist: 'Diplo', 'Thomas Rhett', 'Young Thug', emotion: 'Happy', popularity: 76 },
    { song: 'Bossy (feat. Too $hort)', artist: 'Kelis', 'Too $hort', emotion: 'Happy', popularity: 48 },
    { song: 'Boom - Radio Version', artist: 'Royce Da 5\'9"', emotion: 'Happy', popularity: 45 },
    { song: 'Sab Kuchh Karna', artist: 'Asha Bhosle', 'Satish Batra', emotion: 'Relaxed', popularity: 0 },
    { song: 'Erotic City', artist: 'Prince', emotion: 'Happy', popularity: 51 },
    { song: 'We Getting Money', artist: 'Sheff G', emotion: 'Happy', popularity: 65 },
    { song: 'Cuando Buda Sonríe - Remasterizado', artist: 'Francisco Canaro', emotion: 'Relaxed', popularity: 0 },
    { song: 'Concerto for Orchestra, Sz. 116, BB 123: III. Elegia - Andante non troppo', artist: 'Béla Bartók', 'Fritz Reiner', 'Chicago Symphony Orchestra', emotion: 'Calm', popularity: 14 },
    { song: 'Koi Jab Dard Ka Mara', artist: 'Shamshad Begum', 'Mohammed Rafi', emotion: 'Relaxed', popularity: 0 },
    { song: 'Sommer i Tyrol/Livet er nu engang så', artist: 'Ellen Gottschalch', emotion: 'Calm', popularity: 0 },
    { song: 'Hay Un Ser', artist: 'Antonio Aguilar', emotion: 'Romantic', popularity: 34 },
    { song: 'Thunderstruck - Live - 1991', artist: 'AC/DC', emotion: 'Energetic', popularity: 42 },
    { song: 'Slavonic Dances, Op. 72, B. 147: No. 2, Dumka', artist: 'Antonín Dvořák', 'George Szell', 'Cleveland Orchestra', emotion: 'Sad', popularity: 18 },
    { song: 'Часть 64.3 - За рекой, в тени деревьев', artist: 'Эрнест Хемингуэй', emotion: 'Mellow', popularity: 0 },
    { song: 'No Brainer', artist: 'DJ Khaled', 'Justin Bieber', 'Quavo', 'Chance the Rapper', emotion: 'Energetic', popularity: 74 },
    { song: 'It Could Happen to You', artist: 'Percy Faith', 'Mitch Miller', emotion: 'Sad', popularity: 9 },
    { song: 'Catari - Instrumental', artist: "L'Orchestra Italiana", emotion: 'Sad', popularity: 0 },
    { song: 'Just Imagine It', artist: 'MKTO', emotion: 'Energetic', popularity: 63 },
    { song: 'Inertia Creeps', artist: 'Massive Attack', emotion: 'Energetic', popularity: 52 },
    { song: 'Mountains And Marian', artist: 'Gordon Lightfoot', emotion: 'Relaxed', popularity: 31 },
    { song: 'If Dreams Came True - Single Version', artist: 'Pat Boone', emotion: 'Calm', popularity: 20 },
    { song: 'Six épigraphes antiques, L. 131: II. Pour un tombeau sans nom', artist: 'Claude Debussy', 'Arthur Gold', 'Robert Fizdale', emotion: 'Sad', popularity: 11 },
    { song: 'You Are Love (from "Show Boat")', artist: 'Jerome Kern', 'Mario Lanza', 'Ray Sinatra', emotion: 'Sad', popularity: 0 },
    { song: 'Jerry Springer (Parody of "One Week" by BareNaked Ladies)', artist: '"Weird Al" Yankovic', emotion: 'Happy', popularity: 37 },
    { song: 'Faking It (feat. Kehlani & Lil Yachty)', artist: 'Calvin Harris', 'Kehlani', 'Lil Yachty', emotion: 'Happy', popularity: 63 },
    { song: 'Coplas de la Defensa de Madrid - Remastered', artist: 'Banda Republicana', emotion: 'Relaxed', popularity: 3 },
    { song: 'Swamp - Live', artist: 'Talking Heads', emotion: 'Happy', popularity: 40 },
    { song: 'Over the Rainbow', artist: 'Aretha Franklin', emotion: 'Calm', popularity: 25 },
    { song: 'Ecstacy - 2015 Remaster', artist: 'New Order', emotion: 'Happy', popularity: 39 },
    { song: 'End Of Act 1: Memory', artist: 'Andrew Lloyd Webber', '"Cats" 1981 Original London Cast', 'Elaine Paige', emotion: 'Sad', popularity: 49 },
    { song: 'Marilyn Monroe Mambo', artist: 'Pérez Prado', emotion: 'Energetic', popularity: 12 },
    { song: 'You Really Got A Hold On Me - Remastered 2009', artist: 'The Beatles', emotion: 'Romantic', popularity: 59 },
    { song: 'In Spite Of All The Danger - Anthology 1 Version', artist: 'The Quarrymen', emotion: 'Sad', popularity: 47 },
    { song: 'Padre Nuestro - Remasterizado', artist: 'Francisco Canaro', emotion: 'Calm', popularity: 0 },
    { song: 'Chamko Chamko Bijuriya Chamko', artist: 'Naseem Bano', 'Ashok Kumar', emotion: 'Relaxed', popularity: 0 },
    { song: 'People Say', artist: 'The Dixie Cups', emotion: 'Romantic', popularity: 23 },
    { song: 'Alexander Hamilton', artist: 'Leslie Odom Jr.', 'Anthony Ramos', 'Daveed Diggs', 'Okieriete Onaodowan', 'Lin-Manuel Miranda', 'Phillipa Soo', 'Original Broadway Cast of Hamilton', emotion: 'Mellow', popularity: 70 },
    { song: 'Gut Bucket Blues', artist: 'Louis Armstrong & His Hot Five', emotion: 'Calm', popularity: 5 },
    { song: 'Symphonic Dances from "West Side Story" *: Symphonic Dances from West Side Story: Scherzo (Vivace leggiero)', artist: 'Leonard Bernstein', 'New York Philharmonic', 'West Side Story Original Broadway Cast', emotion: 'Calm', popularity: 14 },
    { song: 'All I Have to Do Is Dream', artist: 'The Everly Brothers', emotion: 'Relaxed', popularity: 67 },
    { song: 'Das ist bei uns nicht möglich, Kapitel 2', artist: 'Sinclair Lewis', 'Frank Arnold', emotion: 'Mellow', popularity: 1 },
    { song: 'In My Bed - So So Def Mix', artist: 'Dru Hill', 'Jermaine Dupri', emotion: 'Happy', popularity: 56 },
    { song: 'Dancing In the Sheets - From "Footloose" Soundtrack', artist: 'Shalamar', emotion: 'Happy', popularity: 50 },
    { song: 'The Diary', artist: 'Neil Sedaka', emotion: 'Romantic', popularity: 30 },
    { song: 'Prelude in B Minor, Op. 13, No. 6: Presto - Remastered', artist: 'Alexander Scriabin', 'Vladimir Horowitz', emotion: 'Calm', popularity: 6 },
    { song: 'Turn the Hands of Time', artist: 'The Intruders', emotion: 'Romantic', popularity: 16 },
    { song: '夫妻相罵', artist: 'Ying Yin Wu', emotion: 'Relaxed', popularity: 2 },
    { song: 'Mamita Mia - Remastered', artist: 'Frente Popular', emotion: 'Relaxed', popularity: 2 },
    { song: 'Ave Maria', artist: 'Céline Dion', emotion: 'Sad', popularity: 41 },
    { song: 'Gente De Accionar', artist: 'Grupo Codiciado', emotion: 'Energetic', popularity: 70 },
    { song: 'The Secret Of My Success', artist: 'Night Ranger', emotion: 'Energetic', popularity: 30 },
    { song: 'Down Poison', artist: '3 Doors Down', emotion: 'Energetic', popularity: 37 },
    { song: 'Overture / Chilkoot Pass', artist: 'Charlie Chaplin', emotion: 'Sad', popularity: 2 },
    { song: 'An Evening Walk', artist: 'Bernward Koch', emotion: 'Sad', popularity: 52 },
    { song: 'Twisting by the Pool', artist: 'Dire Straits', emotion: 'Energetic', popularity: 34 },
    { song: 'New Minglewood Blues - Live; 2008 Remaster', artist: 'Grateful Dead', emotion: 'Happy', popularity: 24 },
    { song: 'Sweet Potato Pie', artist: 'Al Jarreau', emotion: 'Happy', popularity: 23 },
    { song: 'Puccini: Madama Butterfly, Act 2: "Che tua madre dovrà" (Butterfly)', artist: 'Giacomo Puccini', 'Maria Callas', 'Herbert von Karajan', 'Orchestra Del Teatro Alla Scala, Milano', emotion: 'Sad', popularity: 13 },
    { song: 'Whiskey And Wimmen', artist: 'John Lee Hooker', emotion: 'Romantic', popularity: 18 },
    { song: 'Le Bourgeois Gentilhomme – Suite Op.60: III The Fencing Master', artist: 'Richard Strauss', 'London Philharmonic Orchestra', emotion: 'Sad', popularity: 0 },
    { song: 'Moment Of Truth', artist: 'Brandon Mychal Smith', 'Tyler James Williams', emotion: 'Happy', popularity: 44 },
    { song: 'Down The Road Apiece', artist: 'The Rolling Stones', emotion: 'Romantic', popularity: 24 },
    { song: 'No Volvere', artist: 'Gipsy Kings', emotion: 'Relaxed', popularity: 38 },
    { song: 'El Paso', artist: 'Marty Robbins', emotion: 'Romantic', popularity: 23 },
    { song: 'Pledge Pin - 2006 Remaster', artist: 'Robert Plant', emotion: 'Energetic', popularity: 25 },
    { song: 'Hay Ojitos', artist: 'Cornelio Reyna', emotion: 'Romantic', popularity: 32 },
    { song: 'Prime Time', artist: 'The Alan Parsons Project', emotion: 'Happy', popularity: 43 },
    { song: "If You Don't Start Drinkin' (I'm Gonna Leave)", artist: 'George Thorogood & The Destroyers', emotion: 'Energetic', popularity: 32 },
    { song: '忘盡心中情 - 無線電視劇蘇乞兒主題曲', artist: 'Johnny Ip', emotion: 'Calm', popularity: 38 },
    { song: 'Kapitel 11 - In der Osternacht', artist: 'Anton Tschechow', emotion: 'Mellow', popularity: 0 },
    { song: 'Première Gymnopédie', artist: 'Erik Satie', 'Alexandre Tharaud', emotion: 'Calm', popularity: 21 },
    { song: 'One in a Million', artist: 'Dan + Shay', emotion: 'Happy', popularity: 50 },
    { song: 'Tina', artist: 'Frankie Valli & The Four Seasons', emotion: 'Happy', popularity: 0 },
    { song: 'I Got The Blues', artist: 'Clem Snide', emotion: 'Sad', popularity: 25 },
    { song: 'Love in Any Language', artist: 'Sandi Patty', emotion: 'Happy', popularity: 27 },
    { song: 'El Barrendero', artist: 'Rigo Tovar', emotion: 'Happy', popularity: 41 },
    { song: 'The Hucklebuck', artist: 'Chubby Checker', emotion: 'Happy', popularity: 33 },
    { song: 'Una Sera di Tokyo', artist: 'Isao Sasaki', emotion: 'Relaxed', popularity: 0 },
    { song: 'Afrodisiac', artist: 'Brandy', emotion: 'Romantic', popularity: 27 },
    { song: 'It Had To Be You', artist: 'Harry Connick, Jr.', emotion: 'Happy', popularity: 31 },
    { song: 'Two Tribes', artist: 'Frankie Goes To Hollywood', emotion: 'Energetic', popularity: 51 },
    { song: 'Love', artist: 'Musiq Soulchild', emotion: 'Romantic', popularity: 46 },
    { song: 'The Waiting', artist: 'Tom Petty and the Heartbreakers', emotion: 'Energetic', popularity: 46 },
    { song: 'I Like Funky Music', artist: 'Uncle Louie', emotion: 'Happy', popularity: 35 },
    { song: 'Where Did You Go?', artist: 'Boys Night Out', emotion: 'Happy', popularity: 27 },
    { song: 'The Struggle Is Real', artist: 'Marie Digby', emotion: 'Happy', popularity: 0 },
    { song: 'Waiting All Night (feat. Ella Eyre) - Live', artist: 'Rudimental', 'Ella Eyre', emotion: 'Energetic', popularity: 0 },
    { song: 'Move Me No Mountain', artist: 'Love Unlimited', emotion: 'Calm', popularity: 14 },
    { song: 'Step by Step', artist: 'Richie Stephens', emotion: 'Energetic', popularity: 23 },
    { song: 'Nothing But Time - 2006 Remaster', artist: 'Jackson Browne', emotion: 'Relaxed', popularity: 32 },
    { song: 'Reaching', artist: 'Rhye', emotion: 'Romantic', popularity: 30 },
    { song: 'Venus and Mars / Rock Show - 2014 Remaster', artist: 'Paul McCartney', 'Wings', emotion: 'Energetic', popularity: 37 },
    { song: 'I Just Wanna Stop', artist: 'Gino Vannelli', emotion: 'Romantic', popularity: 43 },
    { song: 'I Need Love', artist: 'LL COOL J', emotion: 'Romantic', popularity: 55 },
    { song: 'Low On Air', artist: 'Michael Yezerski', emotion: 'Relaxed', popularity: 0 },
    { song: 'She Caught The Katy', artist: 'The Blues Brothers', emotion: 'Happy', popularity: 44 },
    { song: 'Born in East L.A.', artist: 'Cheech & Chong', emotion: 'Happy', popularity: 26 },
    { song: 'How Deep Is Your Love', artist: 'Sean Paul', emotion: 'Romantic', popularity: 56 },
    { song: 'Somebody Loves Me', artist: 'Perry Como', emotion: 'Happy', popularity: 18 },
    { song: 'Season Of The Witch', artist: 'Joan Jett & The Blackhearts', emotion: 'Energetic', popularity: 41 },
    { song: 'Medal of Honor', artist: 'C. S. Armstrong', emotion: 'Happy', popularity: 25 },
    { song: 'Never Met', artist: 'Cautious Clay', emotion: 'Sad', popularity: 43 },
    { song: 'Summer Days (feat. Macklemore & Patrick Stump of Fall Out Boy)', artist: 'Martin Garrix', 'Macklemore', 'Fall Out Boy', emotion: 'Energetic', popularity: 74 },
    { song: 'Love Me Like That', artist: 'R5', emotion: 'Romantic', popularity: 43 },
    { song: 'Another Part of Me', artist: 'Michael Jackson', emotion: 'Happy', popularity: 52 },
];